name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v2
    - name: Setup Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: v0.4.3
    - name: Clone vader.vim
      uses: actions/checkout@v2
      with:
        repository: junegunn/vader.vim
        path: vader.vim
    - name: Run tests
      run: |
        nvim -Nu <(cat << VIMRC
        filetype off
        set rtp+=vader.vim
        set rtp+=.
        set rtp+=after
        filetype plugin indent on
        syntax enable
        VIMRC) -c 'Vader! test/test_*'
