name: Lint

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: v0.5.0
    - name: Clone vader.vim
      run: |
        git clone https://github.com/junegunn/vader.vim.git
    - name: Run tests
      run: |
        vim -Nu <(cat << VIMRC
        filetype off
        set rtp+=vader.vim
        set rtp+=.
        set rtp+=after
        filetype plugin indent on
        syntax enable
        VIMRC) -c 'Vader! test/test_*'
